# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "chef/ubuntu-14.04"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip:"192.168.2.2"

  # vm name
  config.vm.define :superlist do |t|
  end


  # Provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "playbook/hosts"
    ansible.limit = "vagrant"
    ansible.playbook = "playbook/site.yml"
  end

end
